export type JsonObject = Record<string, unknown>;
export interface CommandInfo { id: string; label: string; menu: string[]; shortcut: string | null; params: string; enabled: boolean; disabled_reason?: string }
export interface ControlSpec { id: string; label: string; section: string; min: number; max: number; default: number; step: number; decimals: number; track: { kind: string; [key: string]: unknown } }
export interface PhotoSummary { id: number; fileName: string; format: string; kind: string; w: number; h: number; captured: string | null; rating: number; flag: 'none'|'pick'|'reject'; label: string | null; edited: boolean; title: string; keywords: string[]; camera: string; deleted: boolean; copyOf?: number|null; copyName?: string; previewOnly?: boolean }
export interface AlbumSummary { id: number; name: string; parent: number|null; count: number; smart: boolean; folder: boolean }
export interface JobStatus { id: string; kind: string; label: string; completed: number; total: number; cancellable: boolean; error?: string }
export interface HostStatus { unsaved: boolean; importing: boolean; exporting: boolean; previewBuild: boolean; jobs: JobStatus[]; notices: string[]; error: string|null }
export interface DesktopSnapshot { version: 1; revision: number; viewGeneration: number; total: number; active: number|null; selection: number[]; source: unknown; filter: unknown; sort: string; commands: CommandInfo[]; controls: ControlSpec[]; controlValues: Record<string, number>; develop: JsonObject; albums: AlbumSummary[]; counts: Record<string, number>; undo: number; redo: number; history: unknown[]; status: HostStatus; libraryPath: string|null; preferences: JsonObject }
export interface ViewSlice { generation: number; total: number; offset: number; photos: PhotoSummary[] }
export interface PreviewRequest { photoId: number; slot: string; viewGeneration: number; width: number; height: number; quality: 'draft'|'full'; before: boolean; sequence: number }
export interface PreviewDescriptor { handle: string; photoId: number; slot: string; viewGeneration: number; sequence: number; key: string; width: number; height: number; histogram: unknown; renderMs: number; encoding: 'png'|'rgba8' }
export type ViewMode = 'photoGrid'|'squareGrid'|'detail'|'compare'|'survey'|'people'|'reference';
export type Panel = 'edit'|'profiles'|'crop'|'remove'|'masking'|'redeye'|'presets'|'info'|'keywords'|'versions'|'activity'|null;
export interface AppSettings { confirmDelete: boolean; gpu: boolean; previewEdge: number; externalEditor: string; memoryMb: number; filmNames: boolean; filmBadges: boolean }
export interface UiState extends AppSettings { view: ViewMode; panel: Panel; tool: string; zoom: 'fit'|'fill'|number; clickZoom: number; beforeAfter: 'off'|'sideBySide'|'split'|'topBottom'|'splitTopBottom'|'original'; sidebarCollapsed: boolean; inspectorCollapsed: boolean; sidebarWidth: number; inspectorWidth: number; thumbSize: number; filmstrip: boolean; filterBar: boolean; referenceId: number|null; compareIds: number[]; navigator: boolean; slideshow: boolean; infoOverlay: number; maskOverlay: boolean; maskOverlayMode: string; maskPins: boolean; clipping: boolean; theme: 'light'|'dark'|'system'; locale: string; sections: Record<string,boolean>; autoAdvance: boolean; gridInfo: boolean; softProof: boolean; brushSize: number; brushFeather: number; cropOverlay: string; filterText: string }
export interface DialogState { kind: string; params?: JsonObject }
export interface DesktopContextValue { snapshot: DesktopSnapshot|null; ui: UiState; setUi: (patch: Partial<UiState>|((ui: UiState)=>Partial<UiState>))=>void; run: (id: string, params?: JsonObject)=>Promise<unknown>; native: (action: string, params?: JsonObject)=>Promise<unknown>; refresh: ()=>Promise<void>; dialog: DialogState|null; setDialog: (dialog: DialogState|null)=>void; error: string|null; notice: string|null; setNotice: (notice: string|null)=>void; histogram: unknown; setHistogram: (histogram: unknown)=>void }
